replicaCount: 2

image:
  # Terraform output se milega registry URL, CI pipeline yahan tag update karega
  repository: asia-south1-docker.pkg.dev/project-c516c2da-ce01-4d29-b05/atm-project-repo/atm-project-app
  tag: v1
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8081

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Rolling update - zero downtime deployment
strategy:
  maxSurge: 1
  maxUnavailable: 0
